spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernatedb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR


welcome:
  message: Hello Mkyong