spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernatedb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none





#    tomcat:
#      max-wait: 20000
#      max-active: 50
#      max-idle: 20
#      min-idle: 15

#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        id:
#          new_generator_mappings: false
#        format_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE